# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.euclidean <- function(Ar, Br) {
    .Call(`_fastDist_euclidean`, Ar, Br)
}

.manhattan <- function(Ar, Br) {
    .Call(`_fastDist_manhattan`, Ar, Br)
}

.minkowski <- function(Ar, Br, p) {
    .Call(`_fastDist_minkowski`, Ar, Br, p)
}

.correlation <- function(Ar, Br) {
    .Call(`_fastDist_correlation`, Ar, Br)
}

.cosine <- function(Ar, Br) {
    .Call(`_fastDist_cosine`, Ar, Br)
}

.canberra <- function(Ar, Br) {
    .Call(`_fastDist_canberra`, Ar, Br)
}

.supremum <- function(Ar, Br) {
    .Call(`_fastDist_supremum`, Ar, Br)
}

.squared_euclidean <- function(Ar, Br) {
    .Call(`_fastDist_squared_euclidean`, Ar, Br)
}

.braycurtis <- function(Ar, Br) {
    .Call(`_fastDist_braycurtis`, Ar, Br)
}

.hellinger <- function(Ar, Br) {
    .Call(`_fastDist_hellinger`, Ar, Br)
}

.chisquared <- function(Ar, Br) {
    .Call(`_fastDist_chisquared`, Ar, Br)
}

.jensenshannon <- function(Ar, Br, base) {
    .Call(`_fastDist_jensenshannon`, Ar, Br, base)
}

.haversine <- function(Ar, Br, radius = 6371.0) {
    .Call(`_fastDist_haversine`, Ar, Br, radius)
}

.standardized_euclidean <- function(Ar, Br, weights = NULL) {
    .Call(`_fastDist_standardized_euclidean`, Ar, Br, weights)
}

.spearman <- function(Ar, Br) {
    .Call(`_fastDist_spearman`, Ar, Br)
}

.mahalanobis <- function(Ar, cov = NULL, regularize = 0.0) {
    .Call(`_fastDist_mahalanobis`, Ar, cov, regularize)
}

.hamming <- function(Ar, Br, threshold = NA_real_) {
    .Call(`_fastDist_hamming`, Ar, Br, threshold)
}

.jaccard <- function(Ar, Br, threshold = 0.0) {
    .Call(`_fastDist_jaccard`, Ar, Br, threshold)
}

.gower <- function(Ar, Br) {
    .Call(`_fastDist_gower`, Ar, Br)
}

