# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.euclidean <- function(Ar, Br) {
    .Call(`_fastDist_euclidean`, Ar, Br)
}

.manhattan <- function(Ar, Br) {
    .Call(`_fastDist_manhattan`, Ar, Br)
}

.minkowski <- function(Ar, Br, p) {
    .Call(`_fastDist_minkowski`, Ar, Br, p)
}

